# -*- coding: utf-8 -*-
"""stock_price_prediction1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O9S3uLsKA0-2aARC4rt2nZcZsHLCP_Pg

# Stock Price Prediction Using LSTM
This Project predicts NSE (National Stock Exchange of India) stock prices using an LSTM deep learning model.  
Data is fetched live from Yahoo Finance using `yfinance`.


**Workflow:**
1. Fetch NSE stock data (e.g., RELIANCE, TCS, INFY)
2. Feature engineering & scaling
3. Sliding window sequence creation
4. LSTM model training
5. Evaluation (MAE, RMSE, Directional Accuracy)
6. Visualization

## 1. Install Dependencies
"""
# Install dependencies separately before running this script
# pip install yfinance scikit-learn tensorflow matplotlib pandas numpy

"""## 2. Import Libraries"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

import yfinance as yf
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping

print("All libraries imported successfully.")

"""## 3. Fetch NSE Stock Data"""

# ── Configuration ──────────────────────────────────────────────
TICKER      = "TCS.NS"   # Change to any NSE ticker (e.g. TCS.NS, INFY.NS)
START_DATE  = "2026-01-01"
END_DATE    = "2026-05-14"
WINDOW_SIZE = 60              # Look-back window (trading days)
EPOCHS      = 20
BATCH_SIZE  = 32
# ───────────────────────────────────────────────────────────────

df = yf.download(TICKER, start=START_DATE, end=END_DATE, progress=False)

if df.empty:
    raise ValueError(f"No data fetched for {TICKER}. Check ticker symbol or date range.")

# Flatten MultiIndex columns if present (yfinance >= 0.2.x)
if isinstance(df.columns, pd.MultiIndex):
    df.columns = df.columns.get_level_values(0)

df = df[['Open', 'High', 'Low', 'Close', 'Volume']].copy()
df.index = pd.to_datetime(df.index)
df.sort_index(inplace=True)

print(f"Ticker : {TICKER}")
print(f"Period : {df.index[0].date()} → {df.index[-1].date()}")
print(f"Rows   : {len(df)}")
df.tail()

"""## 4. Exploratory Data Analysis"""

print("Missing values:")
print(df.isnull().sum())
print()
print(df.describe().round(2))

fig, axes = plt.subplots(2, 1, figsize=(14, 8), sharex=True)

axes[0].plot(df['Close'], color='steelblue', linewidth=1)
axes[0].set_title(f"{TICKER} — Closing Price", fontsize=13)
axes[0].set_ylabel("Price (INR)")
axes[0].grid(alpha=0.3)

axes[1].bar(df.index, df['Volume'], color='darkorange', alpha=0.6, width=1)
axes[1].set_title("Trading Volume", fontsize=13)
axes[1].set_ylabel("Volume")
axes[1].grid(alpha=0.3)

plt.tight_layout()
plt.show()

"""## 5. Feature Engineering"""

# Forward-fill any missing trading days, then drop residual NaNs
df.ffill(inplace=True)
df.dropna(inplace=True)

# Target: next-day closing price
df['next_close'] = df['Close'].shift(-1)
df.dropna(inplace=True)

FEATURES = ['Open', 'High', 'Low', 'Close', 'Volume']
TARGET   = 'next_close'

print(f"Dataset shape after engineering: {df.shape}")
df[[*FEATURES, TARGET]].tail()

"""## 6. Scale Features"""

feature_scaler = MinMaxScaler()
target_scaler  = MinMaxScaler()

scaled_features = feature_scaler.fit_transform(df[FEATURES])
scaled_target   = target_scaler.fit_transform(df[[TARGET]])

print("Feature matrix shape:", scaled_features.shape)
print("Target vector shape :", scaled_target.shape)

"""## 7. Create Sliding Window Sequences"""

def create_sequences(features, targets, window_size):
    """Build (X, y) pairs from a sliding window over the time series."""
    X, y = [], []
    for i in range(window_size, len(features)):
        X.append(features[i - window_size:i])
        y.append(targets[i])
    return np.array(X), np.array(y)

X, y = create_sequences(scaled_features, scaled_target, WINDOW_SIZE)

print(f"X shape: {X.shape}  →  (samples, window, features)")
print(f"y shape: {y.shape}")

"""## 8. Train / Test Split (time-aware)"""

split = int(0.8 * len(X))

X_train, X_test = X[:split], X[split:]
y_train, y_test = y[:split], y[split:]

print(f"Training samples : {len(X_train)}")
print(f"Testing  samples : {len(X_test)}")

"""## 9. Build & Train LSTM Model"""

model = Sequential([
    LSTM(64, return_sequences=True, input_shape=(WINDOW_SIZE, len(FEATURES))),
    Dropout(0.2),
    LSTM(64, return_sequences=False),
    Dropout(0.2),
    Dense(32, activation='relu'),
    Dense(1)
])

model.compile(optimizer='adam', loss='mse', metrics=['mae'])
model.summary()

early_stop = EarlyStopping(
    monitor='val_loss',
    patience=5,
    restore_best_weights=True
)

history = model.fit(
    X_train, y_train,
    epochs=EPOCHS,
    batch_size=BATCH_SIZE,
    validation_data=(X_test, y_test),
    callbacks=[early_stop],
    verbose=1
)

"""## 10. Training Loss Curve"""

plt.figure(figsize=(10, 4))
plt.plot(history.history['loss'],     label='Train Loss')
plt.plot(history.history['val_loss'], label='Val Loss')
plt.title('Model Loss over Epochs')
plt.xlabel('Epoch')
plt.ylabel('MSE Loss')
plt.legend()
plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()

"""## 11. Predictions & Inverse Transform"""

y_pred_scaled = model.predict(X_test)

# Inverse-transform back to INR
y_pred_actual = target_scaler.inverse_transform(y_pred_scaled).flatten()
y_test_actual = target_scaler.inverse_transform(y_test).flatten()

print(f"Prediction samples: {len(y_pred_actual)}")

"""## 12. Evaluation Metrics"""

mae  = mean_absolute_error(y_test_actual, y_pred_actual)
rmse = np.sqrt(mean_squared_error(y_test_actual, y_pred_actual))
mape = np.mean(np.abs((y_test_actual - y_pred_actual) / y_test_actual)) * 100

# Directional accuracy
dir_true = np.sign(np.diff(y_test_actual))
dir_pred = np.sign(np.diff(y_pred_actual))
dir_acc  = np.mean(dir_true == dir_pred) * 100

print("=" * 40)
print(f"  MAE                : ₹{mae:.2f}")
print(f"  RMSE               : ₹{rmse:.2f}")
print(f"  MAPE               : {mape:.2f}%")
print(f"  Directional Acc.   : {dir_acc:.2f}%")
print("=" * 40)

"""## 13. Predicted vs Actual Plot"""

# Align test dates with predictions
test_dates = df.index[WINDOW_SIZE + split:WINDOW_SIZE + split + len(y_test_actual)]

plt.figure(figsize=(14, 6))
plt.plot(test_dates, y_test_actual, label='Actual Close',    color='steelblue',  linewidth=1.5)
plt.plot(test_dates, y_pred_actual, label='Predicted Close', color='darkorange', linewidth=1.5, linestyle='--')
plt.title(f"{TICKER} — Predicted vs Actual Next-Day Closing Price", fontsize=13)
plt.xlabel("Date")
plt.ylabel("Price (INR)")
plt.legend()
plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()

"""## 14. Predict Next Trading Day's Close"""

# Use the last WINDOW_SIZE rows of the full dataset
last_window = scaled_features[-WINDOW_SIZE:].reshape(1, WINDOW_SIZE, len(FEATURES))
next_pred_scaled = model.predict(last_window, verbose=0)
next_pred_price  = target_scaler.inverse_transform(next_pred_scaled)[0, 0]

last_close = df['Close'].iloc[-1]
change_pct = (next_pred_price - last_close) / last_close * 100

print(f"Last available close  : ₹{last_close:.2f}  ({df.index[-1].date()})")
print(f"Predicted next close  : ₹{next_pred_price:.2f}")
print(f"Expected change       : {change_pct:+.2f}%")